import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowDown, Plus, Minus, Menu as MenuIcon, X } from 'lucide-react';
import { Reveal, CursorFollower, ScrollProgress } from './components/Motion';
import DeveloperScene from './components/DeveloperScene';
import ContactForm from './components/ContactForm';
import Work from './sections/Work';
import AiLab from './sections/AiLab';
import { achievements, experience, links, technologies } from './data/profile';
import AmbientBackground from './components/AmbientBackground';
const navigation = [['About', 'about'], ['Capabilities', 'capabilities'], ['AI Lab', 'ai-lab'], ['Work', 'work'], ['Experience', 'experience'], ['Achievements', 'achievements'], ['Currently building', 'building'], ['Contact', 'contact']];

function App() {
  const [menu, setMenu] = useState(false);
  const [intro, setIntro] = useState(() => !sessionStorage.getItem('km-intro'));
  const [capability, setCapability] = useState<number | null>(0);
  const [tech, setTech] = useState(0);
  const [role, setRole] = useState(0);
  const menuRef = useRef<HTMLDivElement>(null);
  const triggerRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { const timer = setTimeout(() => { setIntro(false); sessionStorage.setItem('km-intro','seen'); }, 2100); return () => clearTimeout(timer); }, []);
  useEffect(() => { const timer = window.setInterval(() => setRole((current) => (current + 1) % 4), 2800); return () => window.clearInterval(timer); }, []);
  useEffect(() => {
    if (!menu) return;
    const old = document.body.style.overflow; document.body.style.overflow = 'hidden';
    menuRef.current?.querySelector<HTMLButtonElement>('button')?.focus();
    const key = (event: KeyboardEvent) => { if(event.key==='Escape') setMenu(false); if(event.key==='Tab') { const elements=menuRef.current?.querySelectorAll<HTMLElement>('button,a'); if(!elements?.length) return; const first=elements[0],last=elements[elements.length-1]; if(event.shiftKey && document.activeElement===first) {event.preventDefault();last.focus();} else if(!event.shiftKey && document.activeElement===last) {event.preventDefault();first.focus();} } };
    document.addEventListener('keydown',key); return () => {document.body.style.overflow=old; document.removeEventListener('keydown',key); triggerRef.current?.focus();};
  }, [menu]);
  const closeAndNavigate = (id: string) => { setMenu(false); setTimeout(() => { document.getElementById(id)?.scrollIntoView({behavior:'smooth'}); document.getElementById(id)?.focus({preventScroll:true}); }, 30); };
  return <>
    <AmbientBackground />
    <a className="skip-link" href="#about">Skip to content</a>
    {intro && <div className="intro welcome-intro" aria-hidden="true" onClick={() => setIntro(false)}><p>WELCOME</p></div>}
    <ScrollProgress/><CursorFollower/>
    <header className="header"><a href="#home" className="wordmark" aria-label="Koushick Mondal home">KM<span className="brand-dot">.</span><span className="wordmark-name">KOUSHICK<br/>MONDAL</span></a><div className="header-location"><span className="status-dot"/> KOLKATA, IN <span>22.57° N / 88.36° E</span></div><div className="header-actions"><a href="#contact" className="header-contact">LET’S TALK <ArrowUpRight size={14}/></a><button ref={triggerRef} aria-expanded={menu} aria-controls="navigation" onClick={() => setMenu(true)}>MENU <MenuIcon size={17}/></button></div></header>
    {menu && <div id="navigation" className="menu-overlay" ref={menuRef} role="dialog" aria-modal="true" aria-label="Main navigation"><div className="menu-top"><span className="eyebrow">EXPLORE THE WORLD</span><button onClick={() => setMenu(false)}>CLOSE <X size={20}/></button></div><nav>{navigation.map(([name,id],i)=><a href={`#${id}`} key={id} onClick={e=>{e.preventDefault();closeAndNavigate(id);}}><span>0{i+1}</span>{name}<ArrowUpRight/></a>)}</nav><span className="eyebrow">IDEAS ARE ONLY THE BEGINNING.</span></div>}
    <main>
      <section id="home" className="hero">
        <div className="hero-topline eyebrow"><span>COMPUTER SCIENCE STUDENT / AI·ML / FULL-STACK</span><span>INDEPENDENT MIND. CONNECTED SYSTEMS.</span></div>
        <div className="hero-title"><h1><span>KOUSHICK</span><span>MONDAL<span className="title-period">.</span></span></h1><div className="hero-title-note eyebrow">BUILDING FROM FRONTEND<br/>TO INTELLIGENCE.<span>PORTFOLIO — 2026</span></div></div>
        <div className="hero-art"><DeveloperScene/></div>
        <div className="core-caption eyebrow"><span className="crosshair">+</span> FIG. 001 — DEVELOPER WORKSPACE<span>FRONTEND → API → DATA → AI</span></div>
        <div className="hero-bottom"><div className="hero-description"><span className="eyebrow"><span className="status-dot"/> ALWAYS BUILDING. ALWAYS LEARNING.</span><p>Building intelligent digital products from frontend to backend.</p><div className="hero-ctas"><a className="text-link" href="#work">EXPLORE MY WORK <ArrowDown size={16}/></a><a className="text-link hero-connect" href="#contact">LET’S CONNECT <ArrowUpRight size={16}/></a></div></div><div className="hero-roles eyebrow"><span className="hero-role-label">{['FULL-STACK DEVELOPER','AI ENGINEER','SOFTWARE ENGINEER','FOUNDER'][role]}</span><span className="hero-role-index">0{role + 1} / 04</span></div><a href="#about" className="scroll-cue" aria-label="Scroll to about"><ArrowDown size={21}/><span className="eyebrow">SCROLL TO DISCOVER</span></a></div>
        <div className="hero-baseline eyebrow"><span>BUILT WITH INTENT.</span><span>NOT JUST CODE. POSSIBILITIES.</span><span>01 — 08</span></div>
      </section>
      <section id="about" className="section about" tabIndex={-1}><div className="section-label eyebrow">01 / THE PERSON BEHIND THE SYSTEM</div><Reveal><h2>I TURN COMPLEX<br/>IDEAS INTO <span className="serif-word">real</span><br/><span className="muted">EXPERIENCES.</span></h2></Reveal><div className="about-bottom"><div className="small-coordinate eyebrow">CURIOUS BY NATURE.<br/>ENGINEER BY PRACTICE.<div className="coordinate-art" aria-hidden="true">+<span/>+</div></div><Reveal className="about-copy"><p>I’m Koushick — a Computer Science student and AI/ML & full-stack developer who likes turning “what if” into something you can actually use.</p><p className="secondary-copy">I’m studying Computer Science at Lovely Professional University while building with Python, Generative AI, LangGraph, JavaScript, TypeScript, React, Node.js and databases. From AI experiments to startups, I learn by making things—and making them better.</p><div className="about-meta eyebrow"><span>B.TECH COMPUTER SCIENCE<br/><b>LPU · 2025—2029</b></span><span>FOCUS<br/><b>AI / ML · FULL-STACK</b></span><span>BASED IN<br/><b>KOLKATA, INDIA</b></span></div></Reveal></div></section>
      <section id="capabilities" className="section capabilities" tabIndex={-1}><div className="section-label eyebrow">02 / HOW I BUILD</div><div className="section-heading"><h2>Different disciplines.<br/><span className="muted">One builder’s mindset.</span></h2><span className="eyebrow">CONNECT THE DOTS.<br/>BUILD THE WHOLE THING.</span></div><div className="capability-list">{[
        ['SOFTWARE','Full-stack applications','Interfaces, APIs and databases. Bringing the pieces together into usable web products.','JavaScript / TypeScript / React / Node.js'],
        ['INTELLIGENCE','AI systems','Exploring AI agents, memory and intelligent software that helps people solve real problems.','Python / LangGraph / AI APIs'],
        ['SECURITY','Cybersecurity','Working on proactive defense and threat intelligence as co-founder of CyberHiveX.','Threat intelligence / OSINT / Digital forensics'],
        ['PRODUCT','Idea → reality','Finding a useful problem, shaping the system, then building and improving it.','Architecture / Development / Iteration']
      ].map(([label,title,description,stack],i)=><div className={`capability ${capability===i?'is-open':''}`} key={label}><button onClick={()=>setCapability(capability===i?null:i)} aria-expanded={capability===i} aria-controls={`cap-${i}`}><span className="eyebrow">0{i+1} / {label}</span><span className="cap-title">{title}</span>{capability===i?<Minus/>:<Plus/>}</button><div id={`cap-${i}`} className="cap-details" hidden={capability!==i}><p>{description}</p><span className="eyebrow">{stack}</span></div></div>)}</div></section>
      <AiLab/>
      <Work/>
      <section className="section engineering" id="engineering"><div className="section-label eyebrow">04 / UNDER THE SURFACE</div><Reveal><h2>FROM IDEA<br/>TO <span className="serif-word">system.</span></h2></Reveal><div className="system-flow" aria-label="Engineering process">{['IDEA','ARCHITECTURE','CODE','AI + DATA','DEPLOY','PRODUCT'].map((item,i)=><div key={item}><span className="eyebrow">0{i+1}</span><span className="flow-node"/><strong>{item}</strong></div>)}</div><div className="tech-area"><div><span className="eyebrow">MY WORKING TOOLKIT</span><p className="tech-description" aria-live="polite">{technologies[tech][1]}</p></div><div className="tech-cloud">{technologies.map(([name],i)=><button key={name} className={tech===i?'active':''} onMouseEnter={()=>setTech(i)} onFocus={()=>setTech(i)} onClick={()=>setTech(i)}>{name}<span>↗</span></button>)}</div></div></section>
      <section id="experience" className="section experience" tabIndex={-1}><div className="section-label eyebrow">05 / THE JOURNEY SO FAR</div><div className="section-heading"><h2>LEARNING.<br/>BUILDING. <span className="muted">REPEATING.</span></h2><span className="eyebrow">REAL WORK.<br/>REAL-WORLD PROBLEMS.</span></div><div className="timeline">{experience.map((item)=><Reveal key={item.company} className="timeline-item"><span className="eyebrow timeline-date">{item.date}</span><div><h3>{item.company}</h3><span className="role">{item.role}</span></div><p>{item.text}</p></Reveal>)}</div><p className="community-note">Beyond the code <span>— Community and campus ambassador work with GeeksforGeeks, IIT Bombay and IIT Kharagpur.</span></p></section>
      <section id="achievements" className="section achievements" tabIndex={-1}><div className="section-label eyebrow">06 / A FEW MILESTONES</div><Reveal><h2>THE WORK<br/><span className="serif-word">adds up.</span></h2></Reveal><div className="achievement-list">{achievements.map(([year,title,detail])=><div className="achievement" key={title}><span className="eyebrow">{year}</span><h3>{title}</h3><span>{detail}</span><ArrowUpRight size={20} aria-hidden="true"/></div>)}</div></section>
      <section id="building" className="section building" tabIndex={-1}><div className="section-label eyebrow">07 / NEVER FINISHED</div><div className="building-grid"><div><span className="eyebrow"><span className="status-dot"/> WORK IN PROGRESS IS A GOOD THING.</span><h2>CURRENTLY<br/><span className="muted">BUILDING.</span></h2></div><div className="building-notes"><p>More intelligent systems.<br/>More useful products.<br/>More questions worth exploring.</p><div className="building-tags eyebrow"><span>AI SYSTEMS</span><span>CYBERSECURITY</span><span>GROWBHARAT</span><span>PRODUCT ENGINEERING</span></div></div></div><a className="github-strip" href={links.github} target="_blank" rel="noreferrer"><span className="eyebrow">BUILD IN PUBLIC / GITHUB</span><span>Follow the code.</span><ArrowUpRight/></a><p className="repo-note">Explore repositories on GitHub. No invented contribution counts. Just the work.</p></section>
      <section id="contact" className="section contact" tabIndex={-1}><div className="section-label eyebrow">08 / NEXT STARTS WITH A CONVERSATION</div><div className="contact-top"><span className="eyebrow">HAVE A PROBLEM WORTH SOLVING?</span><span className="eyebrow">LET’S FIND OUT WHAT’S POSSIBLE.</span></div><Reveal><h2>LET’S BUILD<br/>SOMETHING<br/><span className="serif-word">intelligent.</span><a className="contact-arrow" href={links.email} aria-label="Start a conversation by email"><ArrowUpRight/></a></h2></Reveal><div className="contact-bottom"><a className="text-link" href={links.email}>START A CONVERSATION <ArrowUpRight size={18}/></a><a href={links.email} className="email-address">mondalkoushick393@gmail.com</a><div className="social-links"><a href={links.linkedin} target="_blank" rel="noreferrer">LINKEDIN ↗</a><a href={links.github} target="_blank" rel="noreferrer">GITHUB ↗</a></div></div><div className="contact-actions"><a href={links.phone}>CALL +91 89005 00157</a><a href={links.whatsapp} target="_blank" rel="noreferrer">WHATSAPP ↗</a><a href="/resume.pdf">DOWNLOAD RESUME ↓</a></div><ContactForm/></section>
    </main>
    <footer><a href="#home" className="wordmark">KM<span className="brand-dot">.</span></a><span className="eyebrow">KOUSHICK MONDAL<br/><span className="muted">CSE STUDENT / AI·ML / FULL-STACK DEVELOPER</span></span><span className="eyebrow">© {new Date().getFullYear()} · BUILT WITH INTENT.</span><a href="#home" className="eyebrow">BACK TO TOP ↑</a></footer>
  </>;
}
export default App;
